### ISSUE TITLE
Why Test status was showing as broken instead of fail

### ISSUE THREAD

**Issue by RollerIn** [cloudinary/wdio-allure-ts-example#39]
As I saw in the attached allure, the expected values were not matched ..so it was failure scenario and expecting to show in the report as a failure ..but why we are showing as broken? can not we show as failure here?
![image](https://user-images.githubusercontent.com/17290705/155684419-bd9b25e0-8c5b-4520-b761-9e1d84d8778e.png)

**Comment by momoip** [comment]
Hi @RollerIn,
We are checking right now; we will keep you posted on any findings.
Thanks

**Comment by RollerIn** [comment]
one more case , 
Reporter.error("test this should be failed") ...in this case am expecting error and so my test case also should be failed ..but actual is broken

Reporter.error("test this should be failed")
await Reporter.closeStep(true, "trailtest")
in this case also ..same output..that is broken instead of fail

**Comment by FelixZilber** [comment]
Hi @RollerIn, can you send a reproducing example?
